version: '3.3'

services:
  db:
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'library'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'mysql_docker_password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: