version: '3.3'

services:
  db:
    image: mysql:8.1.0
    restart: always
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: 'library'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'mysql_docker_password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  librarian:   
    container_name: librarian
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9205:9205" 
    restart: unless-stopped
    env_file:
      - dev.env
    depends_on:
      - db
volumes:
  my-db: