swagger: "2.0"
info:
    title: Books Service
    description: Service for managing Books with CRUD operations.
    version: ""
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /book:
        post:
            tags:
                - librarian
            summary: create-book librarian
            description: Create a single book.
            operationId: librarian#create-book
            parameters:
                - name: Create-BookRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/LibrarianCreateBookRequestBody'
                    required:
                        - title
                        - author
                        - book_cover
                        - published_at
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/LibrarianCreateBookResponseBody'
            schemes:
                - http
        patch:
            tags:
                - librarian
            summary: update-book librarian
            description: Updates a book by the given id.
            operationId: librarian#update-book
            parameters:
                - name: Update-BookRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/LibrarianUpdateBookRequestBody'
                    required:
                        - title
                        - author
                        - book_cover
                        - published_at
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/LibrarianUpdateBookResponseBody'
            schemes:
                - http
    /book/{id}:
        get:
            tags:
                - librarian
            summary: get-book librarian
            description: Retrieve a book by id.
            operationId: librarian#get-book
            parameters:
                - name: id
                  in: path
                  description: The ID of the book.
                  required: true
                  type: integer
                  minimum: 1
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/LibrarianGetBookResponseBody'
            schemes:
                - http
        delete:
            tags:
                - librarian
            summary: delete-book librarian
            description: Delete a single book.
            operationId: librarian#delete-book
            parameters:
                - name: id
                  in: path
                  description: Book id
                  required: true
                  type: integer
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
    /books/{skip}/{take}:
        get:
            tags:
                - librarian
            summary: get-books librarian
            description: Get paginated books by specifying the number of books to skip and take.
            operationId: librarian#get-books
            parameters:
                - name: skip
                  in: path
                  description: The numbers of records to skip before return.
                  required: true
                  type: integer
                  minimum: 0
                - name: take
                  in: path
                  description: The numbers of records to return.
                  required: true
                  type: integer
                  minimum: 1
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/LibrarianGetBooksResponseBody'
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - librarian
            summary: Download ./gen/http/openapi.json
            operationId: librarian#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    LibrarianCreateBookRequestBody:
        title: LibrarianCreateBookRequestBody
        type: object
        properties:
            author:
                type: string
                description: The author of the book.
                example: t7m
                minLength: 3
                maxLength: 100
            book_cover:
                type: string
                description: The URL to the cover image.
                example: ax
                minLength: 1
                maxLength: 2048
            published_at:
                type: string
                description: The date at which the book was published.
                example: "1973-10-25"
                format: date
            title:
                type: string
                description: The title of the book.
                example: eh
                minLength: 1
                maxLength: 255
        example:
            author: nw1
            book_cover: "3"
            published_at: "2005-06-14"
            title: "y"
        required:
            - title
            - author
            - book_cover
            - published_at
    LibrarianCreateBookResponseBody:
        title: 'Mediatype identifier: createbookresponse; view=default'
        type: object
        properties:
            author:
                type: string
                description: The author of the book.
                example: Amet sunt ea est quam.
            book_cover:
                type: string
                description: The cover image of the book.
                example: Minima sit nam quia culpa iste incidunt.
            id:
                type: integer
                description: The unique id of the book.
                example: 5183068330495628784
                format: int64
            published_at:
                type: string
                description: The date at which the book was published.
                example: Temporibus blanditiis aliquam amet eveniet voluptatibus.
            title:
                type: string
                description: The title of the book.
                example: Omnis esse.
        description: Create-BookResponseBody result type (default view)
        example:
            author: Suscipit molestiae sint quae consectetur nobis.
            book_cover: Voluptas minima labore.
            id: 1159523984026751960
            published_at: Vel qui voluptas consectetur officia.
            title: Magnam molestiae suscipit saepe minus.
        required:
            - id
            - title
            - book_cover
            - author
            - published_at
    LibrarianGetBookResponseBody:
        title: 'Mediatype identifier: getbookresponse; view=default'
        type: object
        properties:
            author:
                type: string
                description: The author of the book.
                example: Illum optio illum laborum.
            book_cover:
                type: string
                description: The cover image of the book.
                example: Provident velit ad unde.
            id:
                type: integer
                description: The unique id of the book.
                example: 3171054538973682877
                format: int64
            published_at:
                type: string
                description: The date at which the book was published.
                example: Est enim explicabo.
            title:
                type: string
                description: The title of the book.
                example: Officia cum.
        description: Get-BookResponseBody result type (default view)
        example:
            author: Natus dolores at qui molestiae molestiae.
            book_cover: Sit quidem laboriosam excepturi.
            id: 6480732628649483770
            published_at: Molestiae voluptas ipsam.
            title: Nostrum et sed dicta ab.
        required:
            - id
            - title
            - book_cover
            - author
            - published_at
    LibrarianGetBooksResponseBody:
        title: 'Mediatype identifier: getbooksresponse; view=default'
        type: object
        properties:
            books:
                $ref: '#/definitions/ResultbookResponseBodyCollection'
        description: Get-BooksResponseBody result type (default view)
        example:
            books:
                - author: Rerum reiciendis delectus eaque.
                  book_cover: Sit rem sequi quidem sint deleniti sed.
                  id: 7065326254943901839
                  published_at: Aut dolorem aut esse nulla nam.
                  title: Illum atque deserunt.
                - author: Rerum reiciendis delectus eaque.
                  book_cover: Sit rem sequi quidem sint deleniti sed.
                  id: 7065326254943901839
                  published_at: Aut dolorem aut esse nulla nam.
                  title: Illum atque deserunt.
                - author: Rerum reiciendis delectus eaque.
                  book_cover: Sit rem sequi quidem sint deleniti sed.
                  id: 7065326254943901839
                  published_at: Aut dolorem aut esse nulla nam.
                  title: Illum atque deserunt.
                - author: Rerum reiciendis delectus eaque.
                  book_cover: Sit rem sequi quidem sint deleniti sed.
                  id: 7065326254943901839
                  published_at: Aut dolorem aut esse nulla nam.
                  title: Illum atque deserunt.
    LibrarianUpdateBookRequestBody:
        title: LibrarianUpdateBookRequestBody
        type: object
        properties:
            author:
                type: string
                description: The author of the book.
                example: 6jq
                minLength: 3
                maxLength: 100
            book_cover:
                type: string
                description: The URL to the cover image.
                example: s0
                minLength: 1
                maxLength: 2048
            id:
                type: integer
                description: The unique id of the book.
                example: 1223066010395007203
                minimum: 1
            published_at:
                type: string
                description: The date at which the book was published.
                example: "1975-06-01"
                format: date
            title:
                type: string
                description: The title of the book.
                example: 8c9
                minLength: 1
                maxLength: 255
        example:
            author: zqz
            book_cover: ik8
            id: 2702213544238060525
            published_at: "2000-06-11"
            title: p
        required:
            - title
            - author
            - book_cover
            - published_at
    LibrarianUpdateBookResponseBody:
        title: 'Mediatype identifier: updatebookresponse; view=default'
        type: object
        properties:
            author:
                type: string
                description: The author of the book.
                example: Itaque et nostrum.
            book_cover:
                type: string
                description: The cover image of the book.
                example: Corporis ipsa expedita eius excepturi perferendis aut.
            id:
                type: integer
                description: The unique id of the book.
                example: 2838318885301413970
                format: int64
            published_at:
                type: string
                description: The date at which the book was published.
                example: Enim optio id et consectetur officiis.
            title:
                type: string
                description: The title of the book.
                example: Mollitia facere.
        description: Update-BookResponseBody result type (default view)
        example:
            author: Libero molestiae nisi eaque.
            book_cover: Autem molestiae beatae eos omnis.
            id: 1634566722588700878
            published_at: Et expedita aut vel.
            title: Molestiae ut cupiditate aut.
        required:
            - id
            - title
            - book_cover
            - author
            - published_at
    ResultbookResponseBody:
        title: 'Mediatype identifier: resultbook; view=default'
        type: object
        properties:
            author:
                type: string
                description: The author of the book.
                example: A est voluptatibus.
            book_cover:
                type: string
                description: The cover image of the book.
                example: Tempora cupiditate iste quia.
            id:
                type: integer
                description: The unique id of the book.
                example: 3976997990927822242
                format: int64
            published_at:
                type: string
                description: The date at which the book was published.
                example: Reprehenderit sint provident quia enim.
            title:
                type: string
                description: The title of the book.
                example: Dolorum facere cupiditate.
        description: ResultbookResponseBody result type (default view)
        example:
            author: Ut ullam ad facilis.
            book_cover: Commodi quo qui ut.
            id: 2276686251063278395
            published_at: Voluptas corrupti.
            title: Eligendi quidem magni quis corporis voluptatum.
        required:
            - id
            - title
            - book_cover
            - author
            - published_at
    ResultbookResponseBodyCollection:
        title: 'Mediatype identifier: resultbook; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/ResultbookResponseBody'
        description: ResultbookCollectionResponseBody is the result type for an array of ResultbookResponseBody (default view)
        example:
            - author: Rerum reiciendis delectus eaque.
              book_cover: Sit rem sequi quidem sint deleniti sed.
              id: 7065326254943901839
              published_at: Aut dolorem aut esse nulla nam.
              title: Illum atque deserunt.
            - author: Rerum reiciendis delectus eaque.
              book_cover: Sit rem sequi quidem sint deleniti sed.
              id: 7065326254943901839
              published_at: Aut dolorem aut esse nulla nam.
              title: Illum atque deserunt.
            - author: Rerum reiciendis delectus eaque.
              book_cover: Sit rem sequi quidem sint deleniti sed.
              id: 7065326254943901839
              published_at: Aut dolorem aut esse nulla nam.
              title: Illum atque deserunt.
            - author: Rerum reiciendis delectus eaque.
              book_cover: Sit rem sequi quidem sint deleniti sed.
              id: 7065326254943901839
              published_at: Aut dolorem aut esse nulla nam.
              title: Illum atque deserunt.
